name: Transfer deploy resources


inputs:
  resources_source:
    description: "Source path to folder with resources"
    required: true

  resources_destination:
    description: "Destination path to folder with resources"
    required: true

  dev-user:
    description: "Username for SSH access to the development server (should be stored as a secret in the repository)"
    required: true

  dev-host:
    description: 'Hostname or IP address of the development server (should be stored as a secret in the repository)'
    required: true


runs:
  using: "composite"
  steps:
    - name: Transfer deploy resources
      shell: bash
      run: |
        ssh ${{ inputs.dev-user }}@${{ inputs.dev-host }} "mkdir -p ${{ inputs.resources_destination }}"
        scp -r ${{ inputs.resources_source }} ${{ inputs.dev-user }}@${{ inputs.dev-host }}:${{ inputs.resources_destination }}
