name: Setup SSH

runs:
  using: "composite"
  steps:
    - name: Setup SSH private key
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.DEV_SSH_KEY }}

    - name: Setup SSH known hosts
      shell: bash
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.DEV_HOST }} >> ~/.ssh/known_hosts