name: Teardown current instance

inputs:
  container_name:
    description: 'Name of the Docker container instance to stop and remove'
    required: true

  dev-user:
    description: "Username for SSH access to the development server (should be stored as a secret in the repository)"
    required: true

  dev-host:
    description: 'Hostname or IP address of the development server (should be stored as a secret in the repository)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Teardown current instance (if exists)
      shell: bash
      run: |
        ssh ${{ inputs.dev-user }}@${{ inputs.dev-host }} "
        docker stop ${{ inputs.container_name }} || true
        docker rm -f ${{ inputs.container_name }} || true
        "