name: Deploy to Dev Stage

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Setup Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      # 3. Build binary
      - name: Build binary
        run: |
          cd cmd/testing/single-peer-setup/
          go build -o single-peer-setup ./...
  

      # 5. Setup SSH key (подрезанный deploy пользователь)
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_KEY }}


      - name: Move Dockerfile
        run: |
          ssh ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }} "mkdir -p /var/www/single-peer-setup"
          
          scp cmd/testing/single-peer-setup/Dockerfile ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }}:/var/www/single-peer-setup/Dockerfile


      - name: Prepare config.json
        run: |
          cd cmd/testing/single-peer-setup/

          sed -i \
            -e 's|PEER_PUBLIC_KEY|${{ secrets.TEST_PEER_PUBLIC_KEY }}|g' \
            -e 's|SERVER_PUBLIC_KEY|${{ secrets.TEST_SERVER_PRIVATE_KEY }}|g' \
            config.json

          scp config.json ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }}:/var/www/single-peer-setup/config.json


      # 7. Deploy container на dev сервере
      - name: Deploy container
        run: |
          scp cmd/testing/single-peer-setup ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }}:/var/www/single-peer-setup/single-peer-setup
          ssh ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }} "
          cd /var/www/single-peer-setup
          docker build -t myapp:dev .
          docker stop single-peer-setup || true
          docker rm single-peer-setup || true
          docker run -d \
            --name single-peer-setup \
            -v /var/www/single-peer-setup:/app/ \
            -p 51830:51830 \
            wg-base:dev
          "