name: Deploy to Dev Stage

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      # 1. Checkout code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Setup Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      # 3. Build binary
      - name: Build binary
        run: |
          cd cmd/testing/wg-setup/
          go build -o app ./...
  

      # 5. Setup SSH key (подрезанный deploy пользователь)
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_KEY }}


      - name: Setup known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DEV_HOST }} >> ~/.ssh/known_hosts


      - name: Move Dockerfile
        run: |
          ssh ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }} "mkdir -p /var/www/wg-setup"
          
          scp cmd/testing/wg-setup/Dockerfile ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }}:/var/www/wg-setup/Dockerfile


      - name: Prepare config.json
        run: |
          cd cmd/testing/wg-setup/

          sed -i \
            -e 's|PEER_PUBLIC_KEY|${{ secrets.TEST_PEER_PUBLIC_KEY }}|g' \
            -e 's|SERVER_PRIVATE_KEY|${{ secrets.TEST_SERVER_PRIVATE_KEY }}|g' \
            config.json

          scp config.json ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }}:/var/www/wg-setup/config.json


      # 7. Deploy container на dev сервере
      - name: Deploy container
        run: |
          ssh ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }} "
          docker stop wg-setup || true
          docker rm -f wg-setup || true
          "
            
          scp cmd/testing/wg-setup/wg-setup ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }}:/var/www/wg-setup/wg-setup
          ssh ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }} "
          cd /var/www/wg-setup
          docker build -t wg-base:dev .
          docker run -d \
            --name wg-setup \
            --cap-add=NET_ADMIN \
            --privileged \
            --cap-add=SYS_MODULE \
            --sysctl net.ipv4.ip_forward=1 \
            --sysctl net.ipv4.conf.all.src_valid_mark=1 \
            -v /var/www/wg-setup/app:/app/app \
            -v /var/www/wg-setup/config.json:/app/config.json \
            -p 51830:51820/udp \
            wg-base:dev
          "