name: "Golang CI"

on: [pull_request]

jobs:
  lint:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.2'
      - name: Lint Go files
        run: gofmt -e .
